### ISSUE TITLE
Hardcoded directory separators: ‘\’

### ISSUE THREAD

**Issue by NotMrFlibble** [zetaPRIME/MultiBound#3]
Depending on environment and Mono settings, this could break things, with Multibound trying to access an object named `..\assets` in the current directory rather than one named `assets` in the directory above.

http://www.mono-project.com/docs/advanced/iomap/ describes this and means of working around this, but as that page says, it's better to use `Path.DirectorySeparator` and `Path.Combine`.

(I understand that Windows copes with mixing `\` and `/` as directory separators. Given that, you _could_, in practice, get away with using `/` everywhere)

**Comment by zetaPRIME** [comment]
Huh. That'd be an issue in FluentPath (I _thought_ I fixed that in my copy... guess that was in a different project from where I copied this)

**Comment by zetaPRIME** [comment]
Wait, no, the hardcoded \ is because I thought all the stock sbinit.config files were the same; on further testing, the game handles "../assets/" on Windows just fine.

**Comment by NotMrFlibble** [comment]
`grep '\\\\' * -rI` tells me that there are still two paths containing `\` in LaunchOld() in MainWindow.cs.

**Comment by zetaPRIME** [comment]
which is never called (and I should probably remove it now that the proper way is done), so that won't be an issue.
